# Generated by Django 3.2.4 on 2021-07-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('head0', models.CharField(max_length=30)),
                ('con_head0', models.CharField(max_length=5000)),
                ('head1', models.CharField(max_length=30)),
                ('con_head1', models.CharField(max_length=5000)),
                ('head2', models.CharField(max_length=30)),
                ('con_head2', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
