# Generated by Django 3.2.4 on 2021-08-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210808_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
